version: "3"

services:
  ghiblidb:
    container_name: ghiblidb
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ghibliapi
    ports:
      - 5432:5432
    expose:
      - 5432
  api:
    container_name: api
    build: .
    command: go run ./cmd/main.go
    environment: 
      - DB_USER=user
      - DB_PASSWORD=secret
      - DB_NAME=ghibliapi
      - DB_HOST=ghiblidb
      - DB_PORT=5432
    ports:
      - 8000:8000
    expose:
      - 8000

    